AllCops:
  DisplayCopNames: true
  Exclude:
    - 'spec/**/*'
    - 'db/*.rb'
    - 'bin/**/*'
    - 'vendor/**/*'

# Common configuration.
Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 115

Style/StringLiterals:
    Enabled: false

Style/AsciiComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false
