#!/bin/bash

# Variables
XDG_CONFIG_HOME="$HOME/.config"
XDG_BIN_HOME="$HOME/.local/bin"
DOTFILES_DIR="$PWD"

create_directories() {
  local directories=("$@")
  for dir in "${directories[@]}"; do
    mkdir -p "$dir"
  done
}

create_symlinks() {
  local items=("$@")
  for item in "${items[@]}"; do
    IFS=':' read -r source target <<<"$item"

    # Handle wildcard patterns
    if [[ "$source" == *"*"* ]]; then
      echo "Processing directory pattern: $source"
      for file in $DOTFILES_DIR/$source; do
        if [ -e "$file" ]; then
          local basename=$(basename "$file")
          local dest="$target$basename"

          if [ -L "$dest" ]; then
            echo "Removing existing symlink $dest"
            unlink "$dest"
          elif [ -e "$dest" ]; then
            echo "Warning: $dest already exists. Skipping..."
            continue
          fi

          ln -s "$file" "$dest"
          echo "Created symlink for $(basename "$file")"
        fi
      done
      continue
    fi

    if [ -L "$target" ]; then
      echo "Removing existing symlink $target"
      unlink "$target"
    elif [ -d "$target" ]; then
      echo "Warning: $target is a directory. Skipping..."
      continue
    elif [ -e "$target" ]; then
      echo "Warning: $target already exists. Skipping..."
      continue
    fi

    ln -s "$DOTFILES_DIR/$source" "$target"
    echo "Created symlink for $source"
  done
}

common_directories=(
  "$XDG_BIN_HOME"
)

common_items=(
  "configs/bashrc:$HOME/.bashrc"
  "configs/bash_profile:$HOME/.bash_profile"
  "configs/bash:$XDG_CONFIG_HOME/bash"
  "configs/git:$XDG_CONFIG_HOME/git"
  "configs/nvim:$XDG_CONFIG_HOME/nvim"
  # "configs/hypr:$XDG_CONFIG_HOME/hypr"
  "configs/sway:$XDG_CONFIG_HOME/sway"
  "configs/mako:$XDG_CONFIG_HOME/mako"
  "configs/mise:$XDG_CONFIG_HOME/mise"
  "configs/swayosd:$XDG_CONFIG_HOME/swayosd"
  "configs/tmux:$XDG_CONFIG_HOME/tmux"
  # "configs/walker:$XDG_CONFIG_HOME/walker"
  "configs/waybar:$XDG_CONFIG_HOME/waybar"
  "configs/alacritty:$XDG_CONFIG_HOME/alacritty"
  "scripts/*:$XDG_BIN_HOME/"
)

create_directories "${common_directories[@]}"
create_symlinks "${common_items[@]}"
