#!/bin/bash

# Variables
XDG_CONFIG_HOME="$HOME/.config"
DOTFILES_DIR="$PWD"

create_directories() {
  local directories=("$@")
  for dir in "${directories[@]}"; do
    mkdir -p "$dir"
  done
}

create_symlinks() {
  local items=("$@")
  for item in "${items[@]}"; do
    IFS=':' read -r source target <<<"$item"
    if [ -L "$target" ]; then
      echo "Removing existing symlink $target"
      unlink "$target"
    elif [ -d "$target" ]; then
      echo "Warning: $target is a directory. Skipping..."
      continue
    elif [ -e "$target" ]; then
      echo "Warning: $target already exists. Skipping..."
      continue
    fi
    ln -s "$DOTFILES_DIR/$source" "$target"
    echo "Created symlink for $source"
  done
}

common_directories=(
  "$HOME/.local/bin"
)

common_items=(
  ".bashrc:$HOME/.bashrc"
  ".bash_profile:$HOME/.bash_profile"
  ".inputrc:$HOME/.inputrc"
  ".config/git:$XDG_CONFIG_HOME/git"
  ".config/nvim:$XDG_CONFIG_HOME/nvim"
  ".config/tmux:$XDG_CONFIG_HOME/tmux"
  ".config/ghostty:$XDG_CONFIG_HOME/ghostty"
  ".config/alacritty:$XDG_CONFIG_HOME/alacritty"
  "scripts/bp-secure-connect:$HOME/.local/bin/bp-secure-connect"
)

create_directories "${common_directories[@]}"
create_symlinks "${common_items[@]}"

# MacOS specific setup
if [[ "$OSTYPE" == darwin* ]]; then
  printf -v ICLOUD "%s" "$HOME/Library/Mobile Documents/com~apple~CloudDocs"
  ln -sf "$ICLOUD" "$HOME/iCloud"
  ln -sf "$ICLOUD/Config/Dotfiles/.aliases" "$HOME/.aliases"

  macos_items=(
    ".config/aerospace:$XDG_CONFIG_HOME/aerospace"
  )

  create_symlinks "${macos_items[@]}"
fi
