import = ["~/.config/alacritty/themes/gruvbox_material_hard_dark.toml"]

[font]
size = 16

[font.normal]
family = "Berkeley Mono Nerd Font"

[window]
decorations = "none"

[window.padding]
x = 7
y = 0
