[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
background = "#1b1b1b"
foreground = "#ebdbb2"

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "Never"

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.glyph_offset]
y = 2

[font.normal]
family = "FiraCode Nerd Font"

[font.offset]
y = 4

[scrolling]
history = 2000

[window]
decorations = "buttonless"
opacity = 0.98

[window.dimensions]
columns = 140
lines = 40

[window.padding]
x = 7
y = 0
