#!/bin/bash

# Variables
export XDG_CONFIG_HOME="$HOME"/.config
export ICLOUD="${HOME}"/Library/Mobile\ Documents/com~apple~CloudDocs

# Directories
mkdir -p "$HOME"/.local/bin

# Symbolic links
ln -sf "$(dirname "$PWD")/.config/nvim" "$XDG_CONFIG_HOME"/nvim
ln -sf "$(dirname "$PWD")/.config/alacritty" "$XDG_CONFIG_HOME"/alacritty
ln -sf "$(dirname "$PWD")/.config/alacritty.toml" "$XDG_CONFIG_HOME"/alacritty.toml
ln -sf "$(dirname "$PWD")/.config/aerospace" "$XDG_CONFIG_HOME"/aerospace
ln -sf "$(dirname "$PWD")/.bash_profile" "$HOME"/.bash_profile
ln -sf "$(dirname "$PWD")/.bashrc" "$HOME"/.bashrc
ln -sf "$(dirname "$PWD")/.inputrc" "$HOME"/.inputrc
ln -sf "$(dirname "$PWD")/.tmux.conf" "$HOME"/.tmux.conf
ln -sf "$PWD/bp-secure-connect" "$HOME"/.local/bin/bp-secure-connect

if [[ "$OSTYPE" == "darwin"* ]]; then
  ln -sf "$ICLOUD" "$HOME"/icloud
  ln -sf "$ICLOUD"/Config/Dotfiles/.aliases "$HOME"/.aliases
fi
